apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cyberark-sidecar-injector
  labels:
    app: cyberark-sidecar-injector
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: sidecar-injector.cyberark.com
    clientConfig:
      service:
        name: cyberark-sidecar-injector
        namespace: ${namespace}
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        cyberark-sidecar-injector: enabled
