apiVersion: v1
kind: Service
metadata:
  annotations:
     service.beta.openshift.io/serving-cert-secret-name: ${serviceName}
  name: ${serviceName}
  namespace: ${namespace}
  labels:
    app: cyberark-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: https
  selector:
    app: cyberark-sidecar-injector
